openapi: 3.0.0
info:
  title: User API
  description: API for user management
  version: "1.0.0"
servers:
  - url: http://localhost:3005
  - url: https://api.catoff.xyz
paths:
  /user/addUserDetails:
    post:
      summary: Add user details
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Email:
                  type: string
                UserName:
                  type: string
              required:
                - Email
                - UserName
      responses:
        '200':
          description: User details added successfully
  /user/login:
    post:
      summary: User login
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signature:
                  type: string
                message:
                  type: string
                publicKey:
                  type: string
              required:
                - signature
                - message
                - publicKey
      responses:
        '200':
          description: Login successful
        '500':
          description: Login failed
